@startuml
'https://plantuml.com/use-case-diagram
left to right direction
actor Guest as "Guest User"
actor User as "Registered User"
actor System as "CPPMoviesServer"

package "CPPMovies"{
    (Display Video Description)
    (Play Video)
    (Pause Video)
    (Rewind Video)
    (Display Subtitles)
    (Search Videos by Name)
    (Search Videos by Category)
    (Filter by Movies)
    (Filter by TV Shows)
    (Adjust Streaming Quality)
    (Manage Profile)
    (View Recommendations)
    (Rate Content)
    (Add to Watchlist)
    (Remove from Watchlist)
    (Browse Catalog)
    (Login)
    (Sign Up)
    (Logout)
    (recommend videos)
}

User --> (Display Video Description)
User --> (Play Video)
User --> (Pause Video)
User --> (Rewind Video)
User --> (Display Subtitles)
User --> (Search Videos by Name)
User --> (Search Videos by Category)
User --> (Filter by Movies)
User --> (Filter by TV Shows)
User --> (Adjust Streaming Quality)
User --> (Manage Profile)
User --> (View Recommendations)
User --> (Rate Content)
User --> (Add to Watchlist)
User --> (Remove from Watchlist)
User --> (Logout)
User --> (Browse Catalog)

Guest --> (Login)
Guest --> (Sign Up)

System --> (recommend videos)
@enduml
